limit_gpu: true
mode: training
training:
  batch_size: 16
  classes:
  - background
  - aeroplane
  - bicycle
  - bird
  - boat
  - bottle
  - bus
  - car
  - cat
  - chair
  - cow
  - diningtable
  - dog
  - horse
  - motorbike
  - person
  - pottedplant
  - sheep
  - sofa
  - train
  - tvmonitor
  csv_log_save_path: ./assets/
  epochs: 2
  img_channels: 3
  img_height: 300
  img_width: 300
  l2_regularization: 0.0005
  learning_rate: 0.001
  n_classes: 20
  pos_iou_threshold: 0.5
  steps_per_epoch: 1000
  train_annotation_dir: ./dataset/training/Annotations/
  train_image_set_filename: ./dataset/training/ImageSets/Main/trainval.txt
  train_img_dir: ./dataset/training/JPEGImages/
  train_load_images_into_memory: true
  val_annotation_dir: ./dataset/test/Annotations/
  val_image_set_filename: ./dataset/test/ImageSets/Main/test.txt
  val_img_dir: ./dataset/test/JPEGImages/
  validation_load_images_into_memory: true
  weight_save_path: ./assets/weights/
